#!/bin/bash
#---------------Script SBATCH - NLHPC ----------------
#SBATCH -J 2chan-six
#SBATCH -p mi210
#SBATCH --gres=gpu:6
#SBATCH --nodes=1
#SBATCH --nodelist=gn005
#SBATCH -n 1
#SBATCH --ntasks-per-node=6
#SBATCH -c 6
#SBATCH --mem=1450000
#SBATCH --mail-user=ariel.argomedo@usach.cl
#SBATCH --mail-type=ALL
#SBATCH -t 2-0:0:0
#SBATCH -o logs/gn004_swin_%j.log
#SBATCH -e logs/gn004_swin_%j.log

# ------------------- Módulos -------------------
ml purge
ml Miniconda3
ml aocc/4.2.0
ml glibc/2.34-zen4-ed5siie

# ------------------- Conda ---------------------
eval "$(conda shell.bash hook)"
conda activate /home/aargomedo/miniconda3/envs/torch_rocm

# ------------------- Entorno PyTorch/ROCm -------
export MASTER_ADDR=$(scontrol show hostname $SLURM_NODELIST | head -n1)
export MASTER_PORT=12345
export WORLD_SIZE=6
export NODE_RANK=$SLURM_NODEID

export OMP_NUM_THREADS=4
export OMP_PLACES=cores

# ROCm
export HSA_FORCE_FINE_GRAIN_PCIE=1
export MIOPEN_FIND_MODE=1
export MIOPEN_DISABLE_FIND_DB=1
export MIOPEN_LOG_LEVEL=1
export HSA_ENABLE_SDMA=1

# PyTorch ROCm memory config
export PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.8,max_split_size_mb:64
export PYTORCH_HIP_ALLOC_CONF=expandable_segments:True

# NCCL ROCm backend (rccl)
export NCCL_DEBUG=INFO
export NCCL_P2P_DISABLE=0
export NCCL_IB_DISABLE=1

# ------------------- Ejecución --------------------
PYTHONWARNINGS="ignore" \

torchrun --nproc_per_node=6 \
         --nnodes=1 \
         --node_rank=$NODE_RANK \
         --master_addr=$MASTER_ADDR \
         --master_port=$MASTER_PORT \
         /home/aargomedo/TESIS/Modelos/Two-Six/Swin/main.py \
         --fits-path /home/aargomedo/TESIS/Modelos/Two-Channel/rutas_fits.txt \
         --cfg configs/swin/swin_base_patch4_window7_224.yaml \
         --accumulation-steps 1

